name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install chromium --with-deps

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:browser
